### ISSUE TITLE
Make "user@realm" authentication work

### ISSUE THREAD

**Issue by pettai** [graylog-labs/graylog-plugin-jabber#6] opened 2015-09-09 10:05 UTC
It's not uncommon that jabber servers require that you specify the user@realm then you authenticate against them. This doesn't seem to work with this plugin. I've also verified my test account(s) with an IM client, and that works fine.

@kroepke also mention earlier that he only got it working leaving out the @realm- part of the username.
"For the record, when testing I had to leave out the domain name from the user account used to authenticate, otherwise I got SASL errors as well, maybe that helps."

**Comment by joschi** [comment] 2015-09-09 10:46
Could you please be a little bit more specific?

* Which XMPP server are you using?
* Which authentication mechanism are you using?
* Is there any (helpful) output from the plugin (you can set `org.graylog2.alarmcallbacks.jabber` to DEBUG level in your `log4j.xml` to get more information)?
* Is there any (helpful) output in the logs of your XMPP server?

**Comment by pettai** [comment] 2015-09-09 17:39
Absolutely,

1) The server(s) are running ejabberd (2.1.10-2ubuntu1.3)  

2) The auth_method configured is "internal", which allows clients to authenticate using the following methods: the old Jabber Non-SASL (XEP-0078), SASL PLAIN, SASL DIGEST-MD5, and SASL SCRAM-SHA-1.  (See http://docs.ejabberd.im/admin/guide/configuration/#internal)

3) log4j.xml settings applied, and the end result looks like this in server.log:

2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] Supported SASL authentications: {org.jivesoftware.smack.sasl.core.SASLXOauth2Mechanism=X-OAUTH2, org.jivesoftware.smack.sasl.javax.SASLCramMD5Mechanism=CRAM-MD5, org.jivesoftware.smack.sasl.javax.SASLGSSAPIMechanism=GSSAPI, org.jivesoftware.smack.sasl.core.SCRAMSHA1Mechanism=SCRAM-SHA-1, org.jivesoftware.smack.sasl.javax.SASLDigestMD5Mechanism=DIGEST-MD5, org.jivesoftware.smack.sasl.javax.SASLExternalMechanism=EXTERNAL, org.jivesoftware.smack.sasl.javax.SASLPlainMechanism=PLAIN}
2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] require_security: false
2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] Security mode: ifpossible
2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] Socket factory: null
2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] Keystore: null
2015-09-09T17:28:02.556Z DEBUG [JabberAlarmCallback] Keystore type: jks
2015-09-09T17:28:07.560Z WARN  [AlertScannerThread] Alarm callback <Jabber Alarm Callback> failed. Skipping.
java.lang.NullPointerException
	at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.call(JabberAlarmCallback.java:125)
	at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:113)
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-09-09T17:28:07.561Z WARN  [AbstractXMPPConnection] Connection closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:994)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
	at java.lang.Thread.run(Thread.java:745)

With or without specifying @realm for the user account, so the subject on this issue is wrong I guess.

AlarmCallback config:
port: 5222
username: gluser (@[myrealm].se)
require_security: false
accept_selfsigned: false
hostname: sp.[myrealm].se
service_name: <empty>
password: ********
recipient: otheruser@[myrealm].se

4) The ejabberd debug output says:

=INFO REPORT==== 2015-09-09 19:27:58 ===
I(<0.467.0>:ejabberd_listener:281) : (#Port<0.1953>) Accepted connection {{109,105,113,XXX},45699} -> {{193,10,5,XXX},5222}
=INFO REPORT==== 2015-09-09 19:27:58 ===
D(<0.498.0>:ejabberd_receiver:320) : Received XML on stream = "<stream:stream xmlns='jabber:client' to='sp.[myrealm].se' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>"
=INFO REPORT==== 2015-09-09 19:27:58 ===
D(<0.499.0>:ejabberd_c2s:1553) : Send XML on stream = [60,63,120,109,108,32,
                                                       118,101,114,115,105,
                                                       111,110,61,39,49,46,48,
                                                       39,63,62,60,115,116,
                                                       114,101,97,109,58,115,
                                                       116,114,101,97,109,32,
                                                       120,109,108,110,115,61,
                                                       39,106,97,98,98,101,
                                                       114,58,99,108,105,101,
                                                       110,116,39,32,120,109,
                                                       108,110,115,58,115,116,
                                                       114,101,97,109,61,39,
                                                       104,116,116,112,58,47,
                                                       47,101,116,104,101,114,
                                                       120,46,106,97,98,98,
                                                       101,114,46,111,114,103,
                                                       47,115,116,114,101,97,
                                                       109,115,39,32,105,100,
                                                       61,39,"1109627481",39,
                                                       32,102,114,111,109,61,
                                                       39,"localhost",39,[],
                                                       [" xml:lang='","en",
                                                        "'"],
                                                       62]
=INFO REPORT==== 2015-09-09 19:27:58 ===
D(<0.499.0>:ejabberd_c2s:1553) : Send XML on stream = <<"<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>">>
=INFO REPORT==== 2015-09-09 19:27:58 ===
D(<0.499.0>:ejabberd_c2s:1553) : Send XML on stream = "</stream:stream>"

HTH,
/P

**Comment by joschi** [comment] 2015-09-10 10:00
@pettai Please try setting `[myrealm].se` as `service_name` (which is using the `hostname` setting otherwise) in your plugin configuration, also see https://xmpp.org/rfcs/rfc6120.html#streams-error-conditions-host-unknown and the explanation there:
> (In the following example, the peer specifies a 'to' address of "example.org" when connecting to the "im.example.com" server, but the server knows nothing of that address.)

**Comment by pettai** [comment] 2015-09-10 12:09
Right, I tried that too and got another error at first.
But this new error seems more promising:

2015-09-10T11:55:02.549Z DEBUG [JabberAlarmCallback] Supported SASL authentications: {org.jivesoftware.smack.sasl.core.SASLXOauth2Mechanism=X-OAUTH2, org.jivesoftware.smack.sasl.javax.SASLCramMD5Mechanism=CRAM-MD5, org.jivesoftware.smack.sasl.javax.SASLGSSAPIMechanism=GSSAPI, org.jivesoftware.smack.sasl.core.SCRAMSHA1Mechanism=SCRAM-SHA-1, org.jivesoftware.smack.sasl.javax.SASLDigestMD5Mechanism=DIGEST-MD5, org.jivesoftware.smack.sasl.javax.SASLExternalMechanism=EXTERNAL, org.jivesoftware.smack.sasl.javax.SASLPlainMechanism=PLAIN}
2015-09-10T11:55:02.550Z DEBUG [JabberAlarmCallback] require_security: false
2015-09-10T11:55:02.550Z DEBUG [JabberAlarmCallback] Security mode: ifpossible
2015-09-10T11:55:02.550Z DEBUG [JabberAlarmCallback] Socket factory: null
2015-09-10T11:55:02.550Z DEBUG [JabberAlarmCallback] Keystore: null
2015-09-10T11:55:02.550Z DEBUG [JabberAlarmCallback] Keystore type: jks
2015-09-10T11:55:02.627Z WARN  [AlertScannerThread] Alarm callback <Jabber Alarm Callback> failed. Skipping.
java.lang.NullPointerException
	at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.call(JabberAlarmCallback.java:125)
	at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:113)
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-09-10T11:55:02.628Z WARN  [AbstractXMPPConnection] Connection closed with error
java.security.cert.CertificateException: Hostname verification of certificate failed. Certificate does not authenticate farscape.se
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:754)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$900(XMPPTCPConnection.java:139)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1001)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
	at java.lang.Thread.run(Thread.java:745)


Now it complains that the certificate doesn't validate against the service name, yet, should this be validated against the hostname in question?
From a usability POW, I think it would be better if service name was automatically extracted from @realm from the username (if @realm was appended on the username)...

**Comment by pettai** [comment] 2015-09-10 15:01
Ok, with a wildcard cert for *.[realm].se on the jabber server I finally received a jabber alert.
This jabber callback plugin is more picky than regular IM clients...

So, from an usability POW It would be good the plugin could accept a certificate that matches "hostname" even if a different "service name" was configured, but I'm uncertain if that goes against anything in the XMPP standard... 
And It would also be good if the service name could be extracted from the username @ realm part automatically, as that's typically how you configure a XMPP client...

**Comment by Flowdalic** [comment] 2015-09-12 12:08
> Now it complains that the certificate doesn't validate against the service name, yet, should this be validated against the hostname in question?

Possible, but not done in practice, because an XMPP service (domain) is potentially hosted by multiple hosts. Current state of the art is to put the XMPP domain as CN. But ideally a subject alternative name (SAN) for the XMPP service name (/XMPP domain) should be used.

> From a usability POW, I think it would be better if service name was automatically extracted from @realm from the username (if @realm was appended on the username).

Note that from XMPP's POV usernames are just opaque "Strings" which may or may not include the username or the users bare JID or something completely different. So this extraction may not always work. A typical XMPP client should ask the user for 2 opaque Strings, "username" (which is in reality a user token) and password, and a XMPP domain (which is subject to normalization). If you ask the user just for his bare JID and the password, then you still don't know if the username is just the localpart of the bare JID or the complete JID. Again XMPP doesn't specify which one to user for (SASL) authentication, so it depends on the server implementation and configuration what is required.

> I don't know if it's a bad idea to have an extra checkbox for allowing the plugin to accept the certificate if it only matches "hostname" or "service name"... (I never saw the certificate issue in my IM client).

Most likely because the IM client isn't as strict as Smack regarding hostname verification. Note that Smack provides `TLSUtils.disableHostnameVerification()` which is perfectly fine to do when CK_ACCEPT_SELFSIGNED is set, since hostname verification is useless in this case anyway.

**Comment by joschi** [comment] 2018-03-01 11:03
The descriptions of the configuration settings for this plugin have been improved to make it more obvious what "Service Name" (now "XMPP Domain Name") means.

Apart from that the issue is pretty old and not really actionable, so I'll close it.

**Closed by joschi** 2018-03-01 11:03 UTC
